"use client";

import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "animate.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { store } from "../redux/store";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: false,
    },
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className="bg-[#F4FCF2] overflow-x-hidden" lang="en">
      <body className={inter.className}>
        <div className="container ">
          <div>
            <Navbar />
          </div>
          <Provider store={store}>
            <QueryClientProvider client={queryClient}>
              <div className="relative top-20 w-screen px-5 lg:px-20 overflow-y-auto max-h-[calc(100vh - 80px)]">
                {children}
              </div>
            </QueryClientProvider>
          </Provider>
        </div>
      </body>
    </html>
  );
}
